### ISSUE TITLE
Campo data pagamento modulo Fatura

### ISSUE THREAD

**Issue by Corteze** [gabriela-castro/Gerenciador-financeiro#20]
Bom dia!
Gostaria de uma ajuda, pois quando clicamos em Pendente em uma fatura criada, e informamos a data de Pagamento, ao clicar em salvar, sempre diz que campo obrigatório deve ser preenchido, no caso o campo data de pagamento!

Outro ponto é que no menu Financeiro, ao clicar em Baixa de Faturas, nada acontece, o módulo baixa não carrega!

obrigado!!

**Comment by AldySalvino** [comment]
Manda os prints para ajudar a entender.

**Comment by Corteze** [comment]
![1](https://user-images.githubusercontent.com/12310749/84410181-48c53b80-abe4-11ea-98cc-72d0fac3bb0b.png)

**Comment by Corteze** [comment]
![2](https://user-images.githubusercontent.com/12310749/84410260-4ebb1c80-abe4-11ea-83bf-fb1da5395be6.png)
![3](https://user-images.githubusercontent.com/12310749/84410294-51b60d00-abe4-11ea-9fe6-07a20c563e61.png)
![4](https://user-images.githubusercontent.com/12310749/84410320-537fd080-abe4-11ea-866f-f567c1f62b57.png)
![5](https://user-images.githubusercontent.com/12310749/84410343-55e22a80-abe4-11ea-90d9-3138f05384f8.png)

**Comment by Corteze** [comment]
na ordem

obrigado, AldySalvino!!!
